# Generated by Django 3.1 on 2020-09-06 13:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('BIODIVERSIDAD', 'Biodiversidad'), ('ARQUEOLOGICO', 'Historia y arqueología'), ('ARQUITECTURA', 'Arquitectura'), ('AGUA', 'Zonas de agua'), ('OTROS', 'Otros'), ('AREA_RECREATIVA', 'Área recreativa'), ('PUNTO_ESPECIAL_INTERES', 'Especial interés'), ('MIRADOR', 'Mirador'), ('GEOLOGIA', 'Geologia')], default='BIODIVERSIDAD', max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=1500, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, max_length=250, verbose_name='Observaciones')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25830)),
            ],
            options={
                'verbose_name': 'Punto de Interés',
                'verbose_name_plural': 'Puntos de Interés',
            },
        ),
    ]
