# Generated by Django 3.1 on 2020-09-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_puntointeres'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntointeres',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
