# Generated by Django 3.1 on 2020-09-07 14:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_puntointeres_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocina', models.CharField(choices=[('CASERA', 'Casera'), ('ASIATICO', 'Asiático'), ('SIDRERIA', 'Sidreria'), ('PIZZERIA', 'Pizzeria'), ('ASADOR', 'Asador')], default='CASERA', max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=254, null=True)),
                ('poblacion', models.CharField(max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25830)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
    ]
