# Generated by Django 3.1 on 2020-09-10 10:54

import core.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200909_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPXFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('gpx_fichero', models.FileField(upload_to=core.models.GPX_Folder)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichero GPX',
                'verbose_name_plural': 'Ficheros GPX',
            },
        ),
        migrations.CreateModel(
            name='GPXTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('SENDEROS_HOMOLOGADOS', 'Senderos homologados'), ('RED_CAMINOS', 'Red de caminos'), ('CAMINOS_NATURALES', 'Caminos naturales'), ('OTROS', 'Otros')], default='SENDEROS_HOMOLOGADOS', max_length=50)),
                ('matricula', models.CharField(choices=[('SL', 'SL'), ('PR', 'PR'), ('GR', 'GR')], default='PR', max_length=50)),
                ('circular', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('dificultad', models.CharField(choices=[('FACIL', 'Fácil'), ('MODERADO', 'Moderado'), ('DIFICIL', 'Difícil')], default='FACIL', max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=250, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, max_length=250, verbose_name='Observaciones')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(dim=3, srid=4326)),
                ('gpx_fichero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gpxfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sendero GPX',
                'verbose_name_plural': 'Senderos GPX',
            },
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Descripción')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sendero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gpxtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto GPX',
                'verbose_name_plural': 'Puntos GPX',
            },
        ),
        migrations.CreateModel(
            name='GPXPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Descripción')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gpx_fichero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gpxfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto GPX',
                'verbose_name_plural': 'Puntos GPX',
            },
        ),
    ]
