# Generated by Django 3.1.1 on 2020-09-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gpxfile_gpxpoint_gpxtrack_trackpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackpoint',
            name='sendero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gpxtrack'),
        ),
    ]
