# Generated by Django 3.1.1 on 2020-09-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200910_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackpoint',
            name='sendero',
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='sendero',
            field=models.ManyToManyField(to='core.GPXTrack'),
        ),
    ]
