# Generated by Django 3.1.1 on 2020-09-13 11:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200910_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.gpxtrack_image_file_path),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.punto_interes_image_file_path),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='modelo3D',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='panorama360',
            field=models.ImageField(blank=True, null=True, upload_to='panoramas/'),
        ),
        migrations.AddField(
            model_name='puntointeres',
            name='tiempo',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='reporte',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.reporte_image_file_path),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.restaurante_image_file_path),
        ),
    ]
