# Generated by Django 3.1.13 on 2021-07-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210724_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuntosInteresImage',
            new_name='PuntoInteresImage',
        ),
    ]
