# Generated by Django 3.1.13 on 2021-07-28 18:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210724_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
