# Generated by Django 3.1.13 on 2021-08-22 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pruebaline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebaline',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(dim=3, srid=4326),
        ),
    ]
