# Generated by Django 3.1.14 on 2022-09-04 09:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.plan_image_file_path),
        ),
    ]
