# Generated by Django 3.1.14 on 2022-10-22 09:09

import core.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220904_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=core.models.storymap_image_file_path)),
                ('descripcion', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storymap',
                'verbose_name_plural': 'Storymaps',
            },
        ),
    ]
