# Generated by Django 3.1.14 on 2022-11-18 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20221118_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntointeres',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
            preserve_default=False,
        ),
    ]
