# Generated by Django 3.1.14 on 2022-11-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20221118_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Modo',
                'verbose_name_plural': 'Modos',
            },
        ),
    ]
