# Generated by Django 3.1.14 on 2023-02-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20230204_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntointeres',
            name='subregion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subregion'),
        ),
    ]
