# Generated by Django 3.1.14 on 2023-02-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20230204_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntointeres',
            name='subregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subregion'),
        ),
        migrations.AlterField(
            model_name='region',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiones', to='core.provincia'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregiones', to='core.region'),
        ),
    ]
