# Generated by Django 3.1.14 on 2023-02-06 08:45

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20230205_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='SubregionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.subregiones_image_file_path)),
                ('subregion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.subregion')),
            ],
            options={
                'verbose_name': 'Material multimedia de las subregiones',
                'verbose_name_plural': 'Materiales multimedia de las subregiones',
            },
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.regiones_image_file_path)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.region')),
            ],
            options={
                'verbose_name': 'Material multimedia de las subregiones',
                'verbose_name_plural': 'Materiales multimedia de las subregiones',
            },
        ),
    ]
