# Generated by Django 3.1.14 on 2023-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20230206_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='subregion',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
