# Generated by Django 3.1.14 on 2023-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_planmovil_savedplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'DetalleReporte',
                'verbose_name_plural': 'DetallesReporte',
            },
        ),
        migrations.CreateModel(
            name='SignoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'SignoReporte',
                'verbose_name_plural': 'SignosReporte',
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'TipoReporte',
                'verbose_name_plural': 'TiposReporte',
            },
        ),
    ]
